config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get "global/switch_lang", as: :switch_lang

  resources :offers do
    collection do
      get :dashboard
    end
  end

  resources :inquiries

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, concerns: :accountable do
    member do
      post :set_current
    end
  end

  resources :users, concerns: :accountable, except: :destroy, :path => "members"

  resources :transfers, only: [:create] do
    member do
      put :delete_reason
    end
  end

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
    end
  end

  resource "statistics" do
    collection do
      get "statistics_global_activity"
      get "statistics_inactive_users"
      get "statistics_demographics"
      get "statistics_last_login"
      get "statistics_without_offers"
      get "statistics_type_swaps"
      get "statistics_all_transfers"
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get "alpha_grouped_index"
      get "inquiries"
      get "offers"
    end
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  AGE_GROUP_LABELS = {
    0..17 => " -17",
    18..24 => "18-24",
    25..34 => "25-34",
    35..44 => "35-44",
    45..54 => "45-54",
    55..64 => "55-64",
    65..100 => "65+",
  }

  before_filter :authenticate_user!

  def statistics_global_activity
    @members = current_organization.members
    @active_members = @members.active
    @total_hours = num_movements = 0
    @members.each do |m|
      num_movements += m.account.movements.count
      @total_hours += m.account.movements.map do
        |a| (a.amount > 0) ? a.amount : 0
      end.inject(0, :+)
    end
    # cada intercambio implica dos movimientos
    @num_swaps = (num_movements +
                  current_organization.account.movements.count) / 2
    # intercambios con el banco
    @total_hours += current_organization.account.movements.
                    map { |a| (a.amount > 0) ? a.amount : 0 }.inject(0, :+)
    # periodo a mostrar actividades globales, por defecto 6 meses
    ini = params[:ini].presence.try(:to_date) || DateTime.now.to_date - 5.month
    fin = params[:fin].presence.try(:to_date) || DateTime.now.to_date
    if ini.present?
      # calculo numero de meses
      num_months = (fin.year * 12 + fin.month) - (ini.year * 12 + ini.month) + 1
      date = ini
      # vector para los meses de la gráfica ["Enero", "Febrero",...]
      @months_names = []
      # y vectores con los datos para la gráfica
      @user_reg_months = []
      @num_swaps_months = []
      @hours_swaps_months = []
      # valores por cada mes
      num_months.times do
        @months_names.push(l(date, format: "%B %Y"))
        @user_reg_months.push(@members.by_month(date).count)
        # movimientos de los miembros en dicho mes
        swaps_members = @members.map { |a| a.account.movements.by_month(date) }
        # movimimentos del banco
        swaps_organization = current_organization.account.
                             movements.by_month(date)
        # numero de movimientos totales
        sum_swaps = (swaps_members.flatten.count + swaps_organization.count) / 2
        @num_swaps_months.push(sum_swaps)
        # horas intercambiadas
        sum_hours = 0
        swaps_members.flatten.each do |s|
          sum_hours += (s.amount > 0) ? s.amount : 0
        end
        sum_hours += swaps_organization.map do
          |a| (a.amount > 0) ? a.amount : 0
        end.inject(0, :+)
        sum_hours = sum_hours / 3600.0 if sum_hours > 0
        @hours_swaps_months.push(sum_hours)
        date = date.next_month
      end
    end
  end

  def statistics_inactive_users
    @members = current_organization.members.active
  end

  def statistics_demographics
    @members = current_organization.members
    @age_counts = age_counts
  end

  def statistics_last_login
    @members = current_organization.members.active.joins(:user).
               order("users.current_sign_in_at ASC NULLS FIRST")
  end

  def statistics_without_offers
    @members = current_organization.members.active
  end

  def statistics_type_swaps
    offers = current_organization.posts.
             where(type: "Offer").joins(:transfers, transfers: :movements).
             select("posts.tags, posts.category_id, SUM(movements.amount) as
                     sum_of_transfers, COUNT(transfers.id) as
                     count_of_transfers").
             where("movements.amount > 0").
             group("posts.tags, posts.category_id, posts.updated_at")

    @offers = count_offers_by_label(offers).to_a.each { |a| a.flatten!(1) }.
              sort_by(&:last).reverse
  end

  def statistics_all_transfers
    @transfers = current_organization.all_transfers.
                 includes(movements: {account: :accountable}).
                 order("transfers.created_at DESC").
                 uniq.
                 page(params[:page]).
                 per(20)
  end

  protected

  def age(date_of_birth)
    return unless date_of_birth
    age_in_days = Date.today - date_of_birth
    (age_in_days / 365.26).to_i
  end

  # returns a hash of
  #     {
  #       [ category_label, tag_label ] => [ sum, count, ratio ],
  #       ...
  #     }
  def count_offers_by_label(offers)
    # Cannot use Hash.new([0, 0]) because then
    #     counters[key][0] += n
    # will modify directly the "global default" instead of
    # first assigning a new array with the zeroed counters.
    counters = Hash.new { |h, k| h[k] = [0, 0] }
    offers.each do |offer|
      labels_for_offer(offer).each do |labels|
        # labels = [ category_label, tag_label ]
        counters[labels][0] += offer.sum_of_transfers
        counters[labels][1] += offer.count_of_transfers
      end
    end
    add_ratios!(counters)
    counters
  end

  def add_ratios!(counters)
    # add the ratio at the end of each value
    total_count = counters.values.map { |_, counts| counts }.sum
    counters.each do |_, v|
      v << v[1].to_f / total_count
    end
  end

  # returns an array of
  #     [category_name, tag_name]
  # one item per each tag. If the category or the tags are missing, they are
  # replaced with a fallback "Unknown" label.
  def labels_for_offer(offer)
    tag_labels = offer.tags.presence ||
                 [t("statistics.statistics_type_swaps.without_tags")]

    category_label = offer.category.try(:name) ||
                     t("statistics.statistics_type_swaps.without_category")

    [category_label].product(tag_labels)
  end

  def age_counts
    @members.each_with_object(Hash.new(0)) do |member, counts|
      age = age(member.user_date_of_birth)
      age_label = AGE_GROUP_LABELS.detect do |range, _|
        range.include? age
      end.try(:last) || t("statistics.statistics_demographics.unknown")
      counts[age_label] += 1
    end
  end
end

app/views/statistics/statistics_all_transfers.html.haml
%h1= t("global.statistics") + ": " + t(".transfers")
.panel.panel-default
  .panel-body
    %table.table.table-hover.table-condensed

      %thead
        %tr
          %th=t(".date")
          %th=t(".from")
          %th=t(".to")
          %th=t(".post")
          %th=t(".reason")
          %th=t(".quantity")
      - @transfers.each do |transfer|
        %tr
          %td= l transfer.created_at, format: :long
          - transfer.movements.sort_by(&:amount).each do |mv|
            %td
              - mv.account.tap do |account|
                - if account.accountable.present?
                  - if account.accountable_type == "Organization"
                    = link_to account,
                    organization_path(account.accountable)
                  - elsif account.accountable.active
                    = link_to account.accountable.display_name_with_uid, user_path(account.accountable.user)
                  - else
                    = t(".inactive_user")
                - else
                  = t(".deleted_user")
          %td
            = link_to_if(transfer.try(:post).try(:active?), transfer.post, transfer.post)
          %td
            = transfer.reason
            - if transfer.reason.present? && admin?
              = link_to delete_reason_transfer_path(transfer), method: :put, data: { confirm: t(".delete_reason") } do
                %span.glyphicon.glyphicon-trash
          %td= seconds_to_hm(transfer.movements.first.amount.abs)

    .paginate-align
      = paginate @transfers

app/views/statistics/statistics_demographics.html.haml
%h1= t("global.statistics") + ": " + t(".demographics")
.panel.panel-default
  .panel-body
    #pie

:javascript
  window.onload = function () {
    // Demograficos
    // Por edades
    var ages = #{ @age_counts.to_a.to_json };
    $('#pie').highcharts({
      chart: {
        plotBackgroundColor: null,
        plotBorderWidth: null,
        plotShadow: false
      },
      title: {
        text: "#{t '.by_ages'}"
      },
      tooltip: {
        pointFormat: '{series.name}: <b>{point.y}</b>'
      },
      plotOptions: {
        pie: {
          allowPointSelect: true,
          cursor: 'pointer',
          dataLabels: {
            enabled: true,
            color: '#000000',
            connectorColor: '#000000',
            format: '<b>{point.name}</b>: {point.percentage:.1f} %'
          }
        }
      },
      series: [{
        type: 'pie',
        name: '#{t '.num_people'}',
        data: ages
      }]
    });
  }

app/views/statistics/statistics_global_activity.html.haml
%h1= t("global.statistics") + ": " + t(".global_activity")
%div{ ng_controller: "" }
  .panel.panel-default
    .panel-body
      %ul.nav.nav-pills.statistics
        %li
          = t ".users_reg"
          .badge
            = @active_members.count
        %li
          = t ".num_swaps"
          .badge
            = @num_swaps
        %li
        = t ".total_hours"
        .badge
          = seconds_to_hm @total_hours
    %form.navbar-form.navbar-right
      .form-group
        %input.form-control{id: "datepicker_from", placeholder: t(".ini_date"), name: "ini", value: params[:ini]}
        %input.form-control{id: "datepicker_to", placeholder: t(".end_date"), name: "fin", value: params[:fin]}
        %button.btn.btn-default{type: :submit}= t(".show")
    #chart

:javascript
  window.onload = function () {
    //globales
    $('#chart').highcharts({
      chart: {
        type: 'column'
      },
      title: {
        text: "#{t '.bank_activity'}"
      },
      subtitle: {
        text: "#{t '.per_month'}"
      },
      xAxis: {
        categories: #{@months_names.to_json}
      },
      yAxis: {
        min: 0,
        title: {
          text: ''
        }
      },
      tooltip: {
        headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
        pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
          '<td style="padding:0"><b>{point.y}</b></td></tr>',
        footerFormat: '</table>',
          shared: true,
          useHTML: true
      },
      plotOptions: {
        column: {
          pointPadding: 0.2,
          borderWidth: 0
        }
      },
      series: [{
        name: "#{t '.users_reg'}",
        data: #{@user_reg_months.to_json}

        }, {
        name: "#{t ".num_swaps"}",
        data: #{@num_swaps_months.to_json}

        }, {
        name: "#{t ".total_hours"}",
        data: #{@hours_swaps_months.to_json}
      }]
    });
  }

app/views/statistics/statistics_inactive_users.html.haml
%h1= t("global.statistics") + ": " + t(".inactive_users")
.panel.panel-default
  .panel-body
    %table.table.table-hover.table-condensed
      %thead
        %tr
          %th ID
          %th= User.human_attribute_name(:username)
          %th= t ".days_without_swaps"
          %th= t ".last_movement"
      %tbody
      / Por días sin movimientos
      - @members.includes(:account).sort_by(&:days_without_swaps).reverse.map{ |a| a unless a.days_without_swaps.zero? }.compact.each do |mem|
        %tr
          %td= mem.member_uid
          %td= link_to mem.user.username, mem.user
          %td= mem.days_without_swaps
          %td= (mem.account.balance.blank? || mem.account.balance.zero?) ? t(".no_movements") : l(mem.account.updated_at, format: :long)

app/views/statistics/statistics_last_login.html.haml
%h1= t("global.statistics") + ": " + t(".last_login")
.panel.panel-default
  .panel-body
    %table.table.table-hover.table-condensed
      %thead
        %tr
          %th ID
          %th= User.human_attribute_name(:username)
          %th= User.human_attribute_name(:last_sign_in_at)
      %tbody
      - @members.each do |mem|
        %tr
          %td= mem.member_uid
          %td= link_to mem.user.username, mem.user
          %td= mem.user.current_sign_in_at.blank? ? t(".never_login") : l(mem.user.current_sign_in_at, format: :long)

app/views/statistics/statistics_type_swaps.html.haml
%h1= t("global.statistics") + ": " + t(".type_of_swaps")
.panel.panel-default
  .panel-body
    %table.table.table-hover.table-condensed
      %thead
        %tr
          %th %
          %th
            = "#{Category.model_name.human} -> #{Offer.human_attribute_name(:tag_list)}"
          %th= t "statistics.statistics_global_activity.total_hours"
          %th= t "statistics.statistics_global_activity.num_swaps"

      %tbody
      / [["Clases", "clases", 13020, 3, 0.30], ["Domestic", "coche", 2220, 1, 0.1],...]
      - @offers.each do |offer|
        %tr
          %td= number_to_percentage(offer.last*100, precision: 2)
          %td= "#{offer[0]} -> #{offer[1]}"
          %td= seconds_to_hm(offer[2] || mdash)
          %td= offer[3]

app/views/statistics/statistics_without_offers.html.haml
%h1= t("global.statistics") + ": " + t(".without_offers")
.panel.panel-default
  .panel-body
    %table.table.table-hover.table-condensed
      %thead
        %tr
          %th ID
          %th= User.human_attribute_name(:username)
      %tbody
      - @members.each do |mem|
        - if mem.offers.blank?
          %tr
            %td= mem.member_uid
            %td= link_to mem.user.username, mem.user