config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get "global/switch_lang", as: :switch_lang

  resources :offers do
    collection do
      get :dashboard
    end
  end

  resources :inquiries

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, concerns: :accountable do
    member do
      post :set_current
    end
  end

  resources :users, concerns: :accountable, except: :destroy, :path => "members"

  resources :transfers, only: [:create] do
    member do
      put :delete_reason
    end
  end

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
    end
  end

  resource "statistics" do
    collection do
      get "statistics_global_activity"
      get "statistics_inactive_users"
      get "statistics_demographics"
      get "statistics_last_login"
      get "statistics_without_offers"
      get "statistics_type_swaps"
      get "statistics_all_transfers"
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get "alpha_grouped_index"
      get "inquiries"
      get "offers"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include LazyRecoverable

  devise *[
    :database_authenticatable,
    # :registerable,
    :recoverable,
    :rememberable,
    :confirmable,
    :lockable,
    :trackable
  ]

  GENDERS = %w[male female]

  attr_accessor :empty_email

  has_many :members, dependent: :destroy
  has_many :organizations, through: :members
  has_many :accounts, through: :members
  has_many :movements, through: :accounts
  has_many :posts
  has_many :offers
  has_many :inquiries

  accepts_nested_attributes_for :members

  default_scope { order("users.id ASC") }
  scope :actives, -> { references(:members).where(members: { active: true }) }
  scope :online_active, -> { where("sign_in_count > 0") }
  scope :notifications, -> { where(notifications: true) }

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  # Allows @domain.com for dummy emails but does not allow pure invalid
  # emails like 'without email'
  validates_format_of :email,
                      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i

  def as_member_of(organization)
    organization && members.find_by(organization: organization)
  end

  def admins?(organization)
    organization && !!(as_member_of(organization).try :manager)
  end
  alias :manages? :admins?

  def superadmin?
    ADMINS.include? email
  end
  alias :superuser? :superadmin?

  def to_s
    "#{username}"
  end

  def user
    self
  end

  def add_to_organization(organization)
    organization && members.
      find_or_create_by(organization: organization) do |member|
      member.entry_date = DateTime.now.utc
    end
  end

  def active?(organization)
    organization && !!(as_member_of(organization).try :active)
  end

  def member(organization)
    members.where(organization_id: organization).first
  end

  def set_dummy_email
    self.email = "user#{id}@example.com"
    skip_reconfirmation! # auto-reconfirm
  end

  def setup_and_save_user
    # check if email is provided or not. If not, flag it and generate
    # temporary valid email with current time milliseconds
    # this will be updated to user.id@example.com later on
    self.empty_email = email.strip.empty?
    self.email = "user#{DateTime.now.strftime('%Q')}@example.com" if empty_email
    skip_confirmation! # auto-confirm, not sending confirmation email
    save
  end

  def tune_after_persisted(organization)
    add_to_organization organization

    # If email was empty, udpate again with user.id just generated
    set_dummy_email if empty_email
    save
  end

  def has_valid_email?
    !email.include? "example.com"
  end

  def email_if_real
    has_valid_email? ? email : ""
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def scoped_users
    current_organization.users
  end

  def index
    @users = scoped_users
    @memberships = current_organization.members.
                   where(user_id: @users.map(&:id)).
                   includes(:account).each_with_object({}) do |mem, ob|
                     ob[mem.user_id] = mem
                   end
  end

  def show
    @user = find_user
    @member = @user.as_member_of(current_organization)
    @movements = @member.movements.order("created_at DESC").page(params[:page]).
                 per(10)
  end

  def new
    authorize User
    @user = scoped_users.build
  end

  def edit
    @user = find_user
  end

  def create
    authorize User

    # New User
    email = user_params[:email]
    @user = User.find_or_initialize_by(email: email) do |u|
      u.attributes = user_params
    end
    empty_email = @user.email.empty?
    @user.setup_and_save_user

    if @user.persisted?
      @user.tune_after_persisted(current_organization)
      redirect_to_after_create
    else
      @user.email = "" if empty_email
      render action: "new"
    end
  end

  def update
    @user = scoped_users.find(params[:id])
    authorize @user

    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render action: :edit, status: :unprocessable_entity
    end
  end

  def give_time
    @user = scoped_users.find(params[:id])
    @destination = @user.members.
                   find_by(organization: current_organization).account.id
    @source = find_transfer_source
    @offer = find_transfer_offer
    @transfer = Transfer.new(source: @source,
                             destination: @destination,
                             post: @offer)
    @sources = find_transfer_sources_for_admin
  end

  private

  def user_params
    fields_to_permit = %w"gender username email date_of_birth phone
                          alt_phone active description notifications"
    fields_to_permit += %w"admin registration_number
                           registration_date" if admin?
    fields_to_permit += %w"organization_id superadmin" if superadmin?
    # params[:user].permit(*fields_to_permit).tap &method(:ap)
    params.require(:user).permit *fields_to_permit
  end

  def find_transfer_offer
    current_organization.offers.
      find(params[:offer]) if params[:offer].present?
  end

  def find_transfer_source
    current_user.members.
      find_by(organization: current_organization).account.id
  end

  def find_transfer_sources_for_admin
    return unless admin?
    [current_organization.account] +
      current_organization.member_accounts.where("members.active is true")
  end

  def find_user
    if current_user.id == params[:id].to_i
      current_user
    else
      scoped_users.find(params[:id])
    end
  end

  def redirect_to_after_create
    id = @user.member(current_organization).member_uid
    if params[:more]
      redirect_to new_user_path,
                  notice: I18n.t("users.new.user_created_add",
                                 uid: id,
                                 name: @user.username)
    else
      redirect_to users_path,
                  notice: I18n.t("users.index.user_created",
                                 uid: id,
                                 name: @user.username)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # TODO refactor or eliminate - poosibly the second.
  def users_as_json
    @users = (admin? || superadmin?) ? @users : @users.actives
    @users.map do |user|
      membership = @memberships[user.id]
      {
        id: user.id,
        avatar: avatar_url(user),
        member_id: membership.member_uid,
        username: user.username,
        email: user.email_if_real,
        unconfirmed_email: user.unconfirmed_email,
        phone: user.phone,
        alt_phone: user.alt_phone,
        balance: membership.account_balance.to_i,

        url: user_path(user),
        edit_link: edit_user_path(user),
        cancel_link: cancel_member_path(membership),
        toggle_manager_link: toggle_manager_member_path(membership),
        manager: !!membership.manager,
        toggle_active_link: toggle_active_member_path(membership),
        active: membership.active?,
        valid_email: user.has_valid_email?
      }
    end.to_json.html_safe
  end

  private

  def edit_user_path(user)
    can_edit_user?(user) ? super : ""
  end

  def can_edit_user?(user)
    superadmin? || admin? || user == current_user
  end

  def cancel_member_path(member)
    can_cancel_member?(member) ? member_path(member) : ""
  end

  def can_cancel_member?(_member)
    superadmin? || admin?
  end

  def toggle_manager_member_path(member)
    can_toggle_manager?(member) ? super : ""
  end

  def can_toggle_manager?(member)
    (superadmin? || admin?) && member.user != current_user
  end

  def toggle_active_member_path(member)
    can_toggle_active?(member) ? super : ""
  end

  def can_toggle_active?(_member)
    superadmin? || admin?
  end
end

app/views/users/_form.html.haml
= show_error_messages!(@user)
= simple_form_for @user do |f|
  .form-inputs

    = f.input :username

    - if admin?
      = f.input :email
      - if @user.unconfirmed_email.present?
        = f.input :unconfirmed_email, readonly: true
    - else
      = f.input :email, readonly: true

    / - if current_user.try :superadmin?
    /   = f.association :organization, include_blank: false
    /   = f.input :superadmin, :as => :boolean, :label => false, :inline_label => true
    / - if current_user.try :admin?
    /   = f.input :admin, :as => :boolean, :label => false, :inline_label => true, hint: t(".admin_warning")

    = f.input :phone
    = f.input :alt_phone
    = f.input :date_of_birth, start_year: Date.today.year - 90, end_year: Date.today.year - 12, include_blank: :true

    = f.input :description, as: "text"
    / = f.association :categories, label_method: :fqn, input_html: {style: 'width: 100%'}

    .checkbox
      = f.label :notifications
      = f.check_box :notifications

  .form-actions
    = f.button :submit
    - if @user.new_record?
      = f.button :submit, t('users.new.create_more_users_button'), name: 'more'
    = link_to t('users.new.cancel'), users_path, class: "btn btn-default"

app/views/users/_user_rows.html.haml
%tr{ "ng-repeat" => "user in users | orderBy:sort | filter:filterTerm", "ng-class" => "{'bg-danger': !user.active}" }
  %td
    %img{ "ng-src" => "{{user.avatar}}", height: "32px", width: "32px" }
  %td {{user.member_id}}
  %td
    %span.glyphicon.glyphicon-time{ "ng-if" => "!user.active" }
    %a{ "ng-href" => "{{user.url}}" }
      {{user.username}}
  %td
    %a{ "ng-href" => "mailto:{{user.email}}", ng_if: "!user.unconfirmed_email"}
      {{user.email}}
    %a{ng_href: "mailto:{{user.unconfirmed_email}}", ng_if: "user.unconfirmed_email"}
      {{user.unconfirmed_email}}
  %td {{user.phone}}
  %td {{user.alt_phone}}
  %td {{user.balance | timeBalance}}
  %td.hover-actions
    %a.action{ "ng-if" => "user.edit_link", "ng-href" => "{{user.edit_link}}"}
      %span.glyphicon.glyphicon-pencil
      = t "global.edit"

    %a.action{ "ng-if" => "user.cancel_link && !user.active", "ng-href" => "{{user.cancel_link}}", :data => {:method => :delete, :confirm => t('.cancel_warning', :user => "{{user.username}}")}}
      %span.glyphicon.glyphicon-ban-circle
      = t "global.cancel_membership"

    %a.action{ href: "", "ng-if" => "user.toggle_manager_link && user.active", "ng-click" => "toggle_manager(user)"}
      %span{ "ng-if" => "user.manager" }
        .glyphicon.glyphicon-arrow-down
        = t "global.demote"
      %span{ "ng-if" => "!user.manager" }
        .glyphicon.glyphicon-arrow-up
        = t "global.promote"

    %a.action{  href: "", "ng-if" => "user.toggle_active_link", "ng-click" => "toggle_active(user)"}
      %span{ "ng-if" => "user.active" }
        .glyphicon.glyphicon-remove
        = t ".deactivate"
      %span{ "ng-if" => "!user.active" }
        .glyphicon.glyphicon-ok
        = t ".activate"

app/views/users/edit.html.haml
%h1
  = @user.username
  %small
    = t ".edit_user"

= render "form"

app/views/users/give_time.html.haml
%h1
  %small= t ".give_time"
  = link_to @user.member(current_organization).display_name_with_uid, user_path(@user)

- if @offer
  %h3= @offer

= simple_form_for @transfer do |f|
  .form-inputs
    = f.input :hours, as: :integer, input_html: { min: 0, max: 20, "data-rule-either-hours-minutes-informed" => "true", "data-rule-range" => "[0,20]"}
    = f.input :minutes, as: :integer, input_html: { min: 0, max: 59, step: 15, "data-rule-either-hours-minutes-informed" => "true", "data-rule-range" => "[0,59]"}
    = f.input :amount, as: :hidden
    = f.input :reason
    = f.input :destination, as: :hidden
    - if admin?
      .form-group
        = f.label :source
        = f.select :source, options_for_select(@sources.sort_by{ |source| [source.accountable_type, source.accountable.try(:member_uid)]}.map{ |a| ["#{a.accountable_type == "Member" ? a.accountable.member_uid : ""} #{a.accountable_type} #{a.accountable.to_s}", a.id]}, selected: current_user.member(current_organization).account.id), {}, { id: "select2-time", class: "form-control" }
    - if @offer
      = f.input :post, readonly: true
      = f.input :post_id, as: :hidden
    - else
      = f.input :post_id, collection: @user.member(current_organization).offers.active

  .form-actions
    = f.button :submit, class: "btn btn-default", style: "margin-bottom: 20px;"

:javascript
  $("#select2-time").select2({
    formatNoMatches: function() {
        return "#{t 'application.tips.user_not_found'}";
    }
  })

app/views/users/index.html.haml
%div{"ng-controller" => "UserListCtrl"}
  %h1
    = User.model_name.human.pluralize
    &mdash;
    = link_to current_organization.name, organization_path(current_organization)
    - if params[:q].present?
      %small
        %span.glyphicon.glyphicon-search
        = params[:q]

  .navbar
    %form.navbar-form.navbar-left
      %input.form-control{type: "text", placeholder: t("global.search"), "ng-model" => "filterTerm"}
    %ul.nav.navbar-nav.pull-right
      - if admin?
        %li
          %a{href: new_user_path}
            %span.glyphicon.glyphicon-plus
            = t "helpers.submit.create", model: User.model_name.human

  %table.table.table-hover.table-condensed.users.panel{"ng-cloak"=>""}
    %thead
      %tr
      %tr
        %th
        %th
          %a{ href: "", ng_click: "sortBy('member_id')" }
            ID
            %span.glyphicon.glyphicon-chevron-down{ ng_if: "sort == '-member_id'" }
            %span.glyphicon.glyphicon-chevron-up{ ng_if: "sort == 'member_id'" }
        %th
          %a{ href: "", ng_click: "sortBy('username')" }
            = User.human_attribute_name(:username)
            %span.glyphicon.glyphicon-chevron-down{ ng_if: "sort == '-username'" }
            %span.glyphicon.glyphicon-chevron-up{ ng_if: "sort == 'username'" }
        %th
          %a{ href: "", ng_click: "sortBy('email')" }
            = User.human_attribute_name(:email)
            %span.glyphicon.glyphicon-chevron-down{ ng_if: "sort == '-email'" }
            %span.glyphicon.glyphicon-chevron-up{ ng_if: "sort == 'email'" }
        %th= User.human_attribute_name(:phone)
        %th= User.human_attribute_name(:alt_phone)
        %th
          %a{ href: "", ng_click: "sortBy('balance')" }
            = Account.human_attribute_name(:balance)
            %span.glyphicon.glyphicon-chevron-down{ ng_if: "sort == '-balance'" }
            %span.glyphicon.glyphicon-chevron-up{ ng_if: "sort == 'balance'" }

        %th
          %span.glyphicon.glyphicon-hand-down
          =t(".actions")
    %tbody
      = render partial: "user_rows", locals: {users: @users}

%script{type: "text/ng-template", id: "confirm_toggle_manager.html"}
  .modal-body= t('.manage_warning_angular')
  .modal-footer
    %button.btn.btn-primary{"ng-click" => "$close(true)"} OK
    %button.btn.btn-warning{"ng-click" => "$dismiss()"} NO

%script{type: "text/ng-template", id: "confirm_toggle_active.html"}
  .modal-body= t('.active_warning_angular')
  .modal-footer
    %button.btn.btn-primary{"ng-click" => "$close(true)"} OK
    %button.btn.btn-warning{"ng-click" => "$dismiss()"} NO

:javascript
  angular.module("timeoverflow").run(function ($rootScope, $location, $http, $modal) {
    $rootScope.users = #{ users_as_json };
  });

app/views/users/index.js.haml
$('table.users tbody').append('#{escape_javascript(render partial: "users/user_rows", locals: { users: @users })}');
$('table.users a[rel=next]').replaceWith('#{link_to_next_page @users, t('.more'), remote: true, class: "btn btn-default", params: params}');

app/views/users/new.html.haml
%h1= t ".new_user"

= render "form"

app/views/users/show.html.haml
.panel.user-profile
  .panel-body
    %h1
      %small
        - unless  @member.active
          = t ".inactive"
      = @member.display_name_with_uid
      %small
        - if @user.superadmin?
          %span.label.label-important= t ".superadmin"

    .row
      .col-sm-3.col-xs-5.text-center
        - if @user == current_user
          %a{href: "https://www.gravatar.com", target: "_blank"}
            = image_tag avatar_url(@user, 160)
        - else
          = image_tag avatar_url(@user, 160)

      .col-sm-9.col-xs-7
        :markdown
          #{@user.description}

        %ul.nav.nav-pills.pull-right
          - if @user == current_user
            %li
              %a{href: edit_user_path(@user)}
                %span.glyphicon.glyphicon-pencil
                = t "global.edit"
          - if admin? || @user != current_user
            %li
              %a{href: give_time_user_path(@user)}
                %span.glyphicon.glyphicon-time
                = t "global.give_time"


        %dl.dl-horizontal
          %h3 
            = t "global.contact_details"
          - if @user.email_if_real != ""
            %dt= User.human_attribute_name(:email)
            %dd= @user.email_if_real
          - phones = [@user.phone, @user.alt_phone].map(&:presence).compact
          - if phones.present?
            %dt= t(".phone", count: phones.size)
            %dd
              - phones.each_with_index do |ph, idx|
                - unless idx.zero?
                  &mdash;
                = ph

.row
  .col-sm-6.offers
    .panel.panel-default
      .panel-heading
        %h2.panel-title
          = Offer.model_name.human(count: :many)
          - if @user == current_user
            %a.pull-right{href: new_offer_path}
              %span.glyphicon.glyphicon-plus


      %table.table.table-condensed.offers
        - @member.offers.active.each do |post|
          %tr
            %td= link_to post, post
            %td= post.description
            %td
              %a{href: give_time_user_path(@user, offer: post.id), title: t("global.give_time")}
                %span.glyphicon.glyphicon-time

  .col-sm-6.inquiries
    .panel.panel-default
      .panel-heading
        %h2.panel-title
          = Inquiry.model_name.human(count: :many)
          - if @user == current_user
            %a.pull-right{href: new_inquiry_path}
              %span.glyphicon.glyphicon-plus

      %table.table.table-condensed.offers
        - @member.inquiries.active.each do |post|
          %tr
            %td= link_to post, post
            %td= post.description

.row
  .col-sm-4
    .panel.panel-default
      .panel-heading
        %h3.panel-title
          = t(".accounts")
      .panel-body
        - if @member.manager
          %p.danger
            ADMIN
        %p
          %strong
            = t(".created_at")
          = @member.entry_date ? l(@member.entry_date, format: :long) : mdash
          %br
          %strong
            = t(".user_no")
          = @member.member_uid || mdash
          %br
          %strong
            = t(".balance")
          = seconds_to_hm(@member.account.try(:balance) || mdash)

.panel.user-profile
  .panel-body
    %h3
      =t(".movements")
    .transactions
      %table.table.table-condensed
        %thead
          %tr
            %th
              =t(".date")
            %th
              =t(".from_to")
            %th
              =t(".post")
            %th
              =t(".reason")
            %th
              =t(".quantity")
        - @movements.each do |mv|
          %tr
            %td= l mv.created_at.to_date, format: :long
            %td
              - mv.other_side.account.tap do |account| 
                - if account.accountable.present?
                  - if account.accountable_type == "Organization"
                    = link_to account,
                              organization_path(account.accountable)
                  - elsif account.accountable.active
                    = link_to account.accountable.display_name_with_uid,
                              user_path(account.accountable.user)
                  - else
                    = t(".inactive_user")
                - else
                  = t(".deleted_user")
            %td
              = mv.transfer.try(:post).try(:active?) ? link_to(mv.transfer.post, offer_path(mv.transfer.post)) : mv.transfer.post
            %td
              = mv.transfer.reason
              - if mv.transfer.reason.present? && admin?
                = link_to delete_reason_transfer_path(mv.transfer), method: :put, data: { confirm: t(".delete_reason") } do
                  %span.glyphicon.glyphicon-trash
            %td= seconds_to_hm(mv.amount)

      .paginate-align
        = paginate @movements