config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  ActiveAdmin.routes(self)

  get "global/switch_lang", as: :switch_lang

  resources :offers do
    collection do
      get :dashboard
    end
  end

  resources :inquiries

  concern :accountable do
    get :give_time, on: :member
  end

  resources :organizations, concerns: :accountable do
    member do
      post :set_current
    end
  end

  resources :users, concerns: :accountable, except: :destroy, :path => "members"

  resources :transfers, only: [:create] do
    member do
      put :delete_reason
    end
  end

  resources :documents

  resources :members, only: [:destroy] do
    member do
      put :toggle_manager
      put :toggle_active
    end
  end

  resource "report" do
    collection do
      get "user_list"
      get "offer_list" => :post_list, type: "offer"
      get "inquiry_list" => :post_list, type: "inquiry"
    end
  end

  resource "statistics" do
    collection do
      get "statistics_global_activity"
      get "statistics_inactive_users"
      get "statistics_demographics"
      get "statistics_last_login"
      get "statistics_without_offers"
      get "statistics_type_swaps"
      get "statistics_all_transfers"
    end
  end

  resource :terms, only: [:show] do
    post :accept
  end

  resources :tags, only: [:index] do
    collection do
      get "alpha_grouped_index"
      get "inquiries"
      get "offers"
    end
  end
end

app/models/offer.rb
class Offer < Post
end

app/controllers/offers_controller.rb
# Managems of offer-type posts
#
class OffersController < PostsController
  def model
    Offer
  end

  def dashboard
    initial_scope =
      if current_organization
        current_organization.offers.active.of_active_members
      else
        Offer.all.active.of_active_members
      end
    @offers = Category.all.sort_by { |a| a.name.downcase }.
              each_with_object({}) do |category, offers|
      list = initial_scope.merge(category.posts).limit(5)
      offers[category] = list if list.present?
    end
  end
end

app/views/offers/dashboard.html.haml
%h1
  = Offer.model_name.human(count: :many)
  = render("/shared/show_filter_hint.html.haml")


.navbar
  %form.navbar-form.navbar-left{action: offers_path, role: "search", method: "get"}
    .form-group
      %input.form-control{type: "text", placeholder: t("global.search"), name: "q", value: params[:q]}
    %button.btn.btn-default{type: "submit"}= t("global.search")

  %ul.nav.navbar-nav
    %li.dropdown
      %a.dropdown-toggle{href: "#"}
        = @category ? @category.name : Category.model_name.human
        %span.caret
      %ul.dropdown-menu{role: "menu"}
        %li= link_to "× #{t("global.all")}", offers_path
        - Category.all.sort_by{ |a| a.name.downcase }.each do |c|
          - next if c == @category
          %li= link_to c.name, offers_path(cat: c.id)

  %ul.nav.navbar-nav.pull-right
    %li
      %a{href: new_offer_path}
        %span.glyphicon.glyphicon-plus
        = t "helpers.submit.create", model: Offer.model_name.human

- @offers.each do |cat, offs|
  .offers
    %h3=cat.name.capitalize
    = render :partial => 'shared/posts', :locals => { :posts => offs }

  = link_to t('global.more'), offers_path(cat: cat.id), :class=>"more btn btn-primary"

app/views/offers/edit.html.haml
%h1
  = @offer.title
  %small
    = t ".edit"

= render partial: 'shared/post_form', locals: { post: @offer, label_button: t(".submit") }

app/views/offers/index.html.haml
%h1
  - @category = Category.where(id: params[:cat]).first
  = Offer.model_name.human(count: :many)
  = render("/shared/show_filter_hint.html.haml")

.navbar
  %form.navbar-form.navbar-left{action: offers_path, role: "search",
                                method: "get"}
    .form-group
      %input.form-control{type: "text", placeholder: t("global.search"),
                          name: "q", value: params[:q]}
    %button.btn.btn-default{type: "submit"}= t("global.search")

  %ul.nav.navbar-nav
    %li.dropdown
      %a.dropdown-toggle{href: "#"}
        = @category ? @category.name : Category.model_name.human
        %span.caret
      %ul.dropdown-menu{role: "menu"}
        %li= link_to "× #{t("global.all")}", dashboard_offers_path
        - Category.all.sort_by { |a| a.name.downcase }.each do |c|
          - next if c == @category
          %li= link_to c.name, offers_path(cat: c.id)

  - if current_user && current_organization && !params[:org]
    %ul.nav.navbar-nav.pull-right
      %li
        %a{href: new_offer_path}
          %span.glyphicon.glyphicon-plus
          = t "helpers.submit.create", model: Offer.model_name.human

.offers
  = render partial: "shared/posts", locals: { posts: @offers }

= paginate @offers

app/views/offers/index.js.haml
$('.offers').append('#{escape_javascript(render partial: "shared/posts", :locals => { :posts => @offers })}');
$('.offers ~ a[rel=next]').replaceWith('#{link_to_next_page @offers, t('.more'), remote: true, params: params}');

app/views/offers/new.html.haml
%h1= t "helpers.submit.create", model: @offer.class.model_name.human

= render partial: 'shared/post_form', locals: {post: @offer, label_button: t(".submit") }

app/views/offers/show.html.haml
= render "shared/post", post: @offer


%p.actions
  - if admin? or @offer.user == current_user
    = link_to edit_offer_path(@offer), class: "btn btn-warning" do
      = glyph :pencil
      = t "global.edit"

    = link_to @offer, data: {method: :DELETE, confirm: "sure?" }, :class => "btn btn-danger" do
      = glyph :trash
      = t "global.delete"
  - if current_user and @offer.user != current_user
    = link_to(give_time_user_path(@offer.user, offer: @offer.id), {:class => "btn btn-success"}) do
      = glyph(:time)
      = t ".give_time_for"